# Setup
title: EBrichford's Blog
tagline: Some day soon this will have a better title
url: https://elliottbrichford.com
paginate: 1
baseurl: ""
permalink: :title/

kramdown:
    footnote_backlink: "&#10548;"

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-target-blank

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

ga_analytics: UA-59340680-1

# Specify the author for blog posts
author:
  name: Elliott Brichford
  url: https://twitter.com/essentialenemy
  email: elliott@elliottbrichford.com

# Custom vars
version: 1.3.0
github:
  repo: https://github.com/BrichfoE/brichfoe.github.io
